version: 2
jobs:
  build:
    working_directory: ~/code

    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout

      - restore_cache:
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum "retrofit-converter-thrifty/build.gradle.kts" }}

      - run:
          name: Download Dependencies
          command: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum "retrofit-converter-thrifty/build.gradle.kts" }}

      - run:
          name: Run Tests
          command: ./gradlew check

      - run:
          name: Upload Test Coverage
          command: bash <(curl -s https://codecov.io/bash)

      - store_test_results:
          path: retrofit-converter-thrifty/build/test-results
